server:
  port: 8080
spring:
  application:
    name: cloud-grpc-client
  sleuth:
    sampler:
      probability: 1.0
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/